export const properties = {
  header: "Featured Properties",
  description:
    "Discover handpicked properties that match your preferences with our AI-powered recommendations",
  data: [
    {
      id: "1",
      title: "Modern Downtown Loft",
      location: "Manhattan, New York",
      type: "Apartment",
      typeI: "ph:building-apartment-fill",
      price: "$2,850/mo",
      beds: 2,
      baths: 2,
      size: 1200,
      rating: 4.9,
      forRent: true,
      forSale: false,
      aiRecommended: true,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      image: "/src/assets/feature-1.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
      ],
    },
    {
      id: "2",
      title: "Luxury Waterfront Apartment",
      location: "Miami Beach, FL",
      type: "villa",
      typeI: "ic:round-villa",
      price: "$4,200/mo",
      beds: 3,
      baths: 2,
      size: 1800,
      rating: 4.8,
      forRent: false,
      forSale: true,
      aiRecommended: false,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      image: "/src/assets/feature-4.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
        { title: "Pool", icon: "ph:swimming-pool" },
      ],
    },
    {
      id: "3",
      title: "Modern Downtown Loft",
      location: "Manhattan, New York",
      type: "Studio",
      typeI: "cbi:bedroom",
      price: "$2,850/mo",
      beds: 2,
      baths: 2,
      size: 1200,
      rating: 4.9,
      aiRecommended: true,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      forRent: true,
      forSale: false,
      image: "/src/assets/feature-1.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
      ],
    },
    {
      id: "4",
      title: "Luxury Waterfront Apartment",
      type: "villa",
      typeI: "ic:round-villa",
      location: "Miami Beach, FL",
      price: "$4,200/mo",
      beds: 3,
      baths: 2,
      size: 1800,
      rating: 4.8,
      aiRecommended: false,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      forRent: true,
      forSale: false,
      image: "/src/assets/feature-4.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
        { title: "Pool", icon: "ph:swimming-pool" },
      ],
    },
    {
      id: "5",
      title: "Modern Downtown Loft",
      type: "villa",
      typeI: "ic:round-villa",
      location: "Manhattan, New York",
      price: "$2,850/mo",
      beds: 2,
      baths: 2,
      size: 1200,
      rating: 4.9,
      aiRecommended: true,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      forRent: false,
      forSale: true,
      image: "/src/assets/feature-1.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
      ],
    },
    {
      id: "6",
      title: "Luxury Waterfront Apartment",
      location: "Miami Beach, FL",
      type: "Studio",
      typeI: "cbi:bedroom",
      price: "$4,200/mo",
      beds: 3,
      baths: 2,
      size: 1800,
      rating: 4.8,
      aiRecommended: false,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      forRent: true,
      forSale: false,
      image: "/src/assets/feature-4.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
        { title: "Pool", icon: "ph:swimming-pool" },
      ],
    },
    {
      id: "7",
      title: "Luxury Waterfront Apartment",
      location: "Miami Beach, FL",
      type: "Apartment",
      typeI: "ph:building-apartment-fill",
      price: "$4,200/mo",
      beds: 3,
      baths: 2,
      size: 1800,
      rating: 4.8,
      aiRecommended: false,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      forRent: true,
      forSale: false,
      image: "/src/assets/feature-4.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
        { title: "Pool", icon: "ph:swimming-pool" },
      ],
    },
    {
      id: "8",
      title: "Luxury Waterfront Apartment",
      type: "Apartment",
      typeI: "ph:building-apartment-fill",
      location: "Miami Beach, FL",
      price: "$4,200/mo",
      beds: 3,
      baths: 2,
      size: 1800,
      rating: 4.8,
      aiRecommended: false,
      agent: {
        name: "Sarah Johnson",
        title: "Senior Property Consultant",
        rating: 4.9,
        reviews: 150,
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        phone: "+971 55 123 4567",
        email: "sarah.johnson@example.com",
      },
      image: "/src/assets/feature-4.jpeg",
      added: [
        { title: "Wifi", icon: "famicons:wifi-outline" },
        { title: "Parking", icon: "fluent-mdl2:parking-mirrored-solid" },
        { title: "Gym", icon: "fluent:dumbbell-28-regular" },
        { title: "Pool", icon: "ph:swimming-pool" },
      ],
    },
  ],
};
export const Whychoose = {
  header: "Why Choose Our Platform",
  description:
    "Experience the future of property search with cutting-edge AI technology that makes finding your perfect home easier than ever",
  data: [
    {
      title: "AI Recommendations",
      description:
        "Get personalized apartment suggestions based on your preferences, search history, and lifestyle needs.",
      icon: "hugeicons:brain-01",
      bg: "bg-primary text-beige rounded-xl w-15",
      w: 40,
    },
    {
      title: "Advanced Filtering",
      description:
        "Use intelligent filters to refine your property search with precise criteria and smart suggestion.",
      icon: "mdi:filter-outline",
      bg: "bg-beige text-primary rounded rounded-xl w-15",
      w: 40,
    },
    {
      title: "AR/VR Viewing",
      description:
        "Take immersive virtual tours and use augmented reality to see how properties would look furnished",
      icon: "mdi:eye-outline",
      bg: "bg-beige text-primary rounded-xl w-15",
      w: 40,
    },
    {
      title: "AI Virtual Staging",
      description:
        "Visualize empty rooms with different furniture styles and layouts powered by artificial intelligence",
      icon: "mdi:palette",
      bg: "bg-primary text-beige rounded-xl w-15",
      w: 40,
    },
  ],
};

export const categories = {
  header: "Explore Property Categories",
  description:
    "Browse through our diverse range of properties to find exactly what you’re looking for",
  data: [
    {
      title: "For Sale",
      description: "Find your dream home to buy",
      icon: "mdi:home",
      bg: "bg-primary text-beige rounded-full w-12",
    },
    {
      title: "For Rent",
      description: "Discover Rental Properties",
      icon: "mdi:key",
      bg: "bg-beige text-primary rounded-full w-12",
    },
    {
      title: "Furnished Apartments",
      description: "Move-in ready spaces",
      icon: "mdi:bed",
      bg: "bg-primary text-beige rounded-full w-12",
    },
    {
      title: "Luxury Villas",
      description: "Premium properties",
      icon: "mdi:star",
      bg: "bg-beige text-primary rounded-full w-12",
    },
    {
      title: "Student Housing",
      description: "Perfect for students",
      icon: "mdi:school",
      bg: "bg-primary text-beige rounded-full w-12",
    },
    {
      title: "Commercial",
      description: "Office & retail spaces",
      icon: "mdi:cash",
      bg: "bg-beige text-primary rounded-full w-12",
    },
  ],
};
export const popularLocations = [
  "New cairo",
  "6th october",
  "Maadi",
  "Zamalek",
  "Noath Coast",
];
